CREATE TABLE IF NOT EXISTS vendors (
    vendor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    company VARCHAR(255) NOT NULL UNIQUE,
    register_timestamp TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS purchasers (
    purchaser_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    birth_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    vendor_id INTEGER,
    CONSTRAINT fk_products_vendor FOREIGN KEY (vendor_id) REFERENCES vendors(vendor_id)
);

-- Purchases
CREATE TABLE IF NOT EXISTS purchases (
    purchase_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER,
    purchaser_id INTEGER,
    CONSTRAINT fk_purchases_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT fk_purchases_purchaser FOREIGN KEY (purchaser_id) REFERENCES purchasers(purchaser_id)
);

TRUNCATE TABLE
    purchases,
    products,
    purchasers,
    vendors
RESTART IDENTITY CASCADE;
